version: 1.0.{build}

image: Ubuntu

install:
  - sh: sudo apt-get update
  - sh: echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - sh: curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
  - sh: sudo apt-get update
  - sh: sudo apt-get install sbt

build_script:
  - sbt compile
  
test_script:
  - sbt test

